name: Linter

on:
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Resharp
        uses: glassechidna/resharper-action@master
        with:
          solution: Remote Healthcare.sln
